const items = [
  {
    id: 10000,
    barcode: '*10000*',
    title: 'Brady Boyd - Finding the Right Balance with Time',
    talk: 'Finding the Right Balance with Time',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'Chapel',
    subtitle: 'Brookfield',
    speaker: 'Brady Boyd',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10001,
    barcode: '*10001*',
    title: 'Brian Sonderman - The Workday Weekday Blues',
    talk: 'The Workday Weekday Blues',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'B329-332',
    subtitle: 'Brookfield',
    speaker: 'Brian Sonderman',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10002,
    barcode: '*10002*',
    title: 'Brian Marvel - Adversity',
    talk: 'Adversity',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'B223-226',
    subtitle: 'Brookfield',
    speaker: 'Bryan Marvel',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10003,
    barcode: '*10003*',
    title: 'Carlos Whittaker - Kill the Spider',
    talk: 'Kill the Spider',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'Auditorium',
    subtitle: 'Brookfield',
    speaker: 'Carlos Whittaker',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10004,
    barcode: '*10004*',
    title: 'Casey Seymour - Parenting Through the Seasons',
    talk: 'Parenting Through the Seasons',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'B321-324',
    subtitle: 'Brookfield',
    speaker: 'Casey Seymour',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10005,
    barcode: '*10005*',
    title: 'Colleen Sonderman - Top Ten Things Every Wife Wishes Her Husband Knew',
    talk: 'Top Ten Things Every Wife Wishes Her Husband Knew',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'B231-232',
    subtitle: 'Brookfield',
    speaker: 'Colleen Sonderman',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10006,
    barcode: '*10006*',
    title: 'Elie Hasbani - Biblical Healing for Past Wounds',
    talk: 'Biblical Healing for Past Wounds',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'D166-167',
    subtitle: 'Brookfield',
    speaker: 'Elie Hasbani',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10007,
    barcode: '*10007*',
    title: 'Erick Lettner - Meeting Jesus for the First Time',
    talk: 'Meeting Jesus for the first time',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'B229',
    subtitle: 'Brookfield',
    speaker: 'Erick Lettner',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10008,
    barcode: '*10008*',
    title: 'Lee Heyward - When Conflict Collides With...Your Happily Ever After',
    talk: 'When Conflict Collides With...Your Happily Ever After',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'B325-328',
    subtitle: 'Brookfield',
    speaker: 'Lee Heyward',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10009,
    barcode: '*10009*',
    title: 'Matthew Malone - Forgiveness',
    talk: 'Forgiveness',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'Fellowship Hall',
    subtitle: 'Brookfield',
    speaker: 'Matthew Malone',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10010,
    barcode: '*10010*',
    title: "Ned Frost and Ron Fickel, MD - Men's Health",
    talk: "Men's Health",
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'B227',
    subtitle: 'Brookfield',
    speaker: 'Ned Frost and Ron Fickel, MD',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10011,
    barcode: '*10011*',
    title: 'Nic Gibson - Sexual Identity',
    talk: 'Sexual Identity',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'B228',
    subtitle: 'Brookfield',
    speaker: 'Nic Gibson',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10012,
    barcode: '*10012*',
    title: 'Norm Hubbard - A Growing Prayer Life',
    talk: 'A Growing Prayer Life',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'B334-336',
    subtitle: 'Brookfield',
    speaker: 'Norm Hubbard',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10013,
    barcode: '*10013*',
    title: 'Paul Stevens - Biblical Manhood',
    talk: 'Biblical Manhood',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'Amphitheater',
    subtitle: 'Brookfield',
    speaker: 'Paul Stevens',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10014,
    barcode: '*10014*',
    title: 'Spanish 1',
    talk: 'Spanish 1',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'D168',
    subtitle: 'Brookfield',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10015,
    barcode: '*10015*',
    title: 'Albert Tate - Uncommon Parenting',
    talk: 'Uncommon Parenting',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'Chapel',
    subtitle: 'Brookfield',
    speaker: 'Albert Tate',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10016,
    barcode: '*10016*',
    title: 'Brian Episcopo - I am a parent, now what?',
    talk: 'I am a parent, now what?',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'B229',
    subtitle: 'Brookfield',
    speaker: 'Brian Episcopo',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10017,
    barcode: '*10017*',
    title: 'Brian & Melissa Hofmeister - Intimacy in Marriage',
    talk: 'Intimacy in Marriage',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'B231-232',
    subtitle: 'Brookfield',
    speaker: 'Brian and Melissa Hofmeister',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10018,
    barcode: '*10018*',
    title: 'Jeff Jaeger - Sharing His Story while Sharing Yours',
    talk: 'Sharing His Story while Sharing Yours',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'B321-324',
    subtitle: 'Brookfield',
    speaker: 'Jeff Jaeger',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10019,
    barcode: '*10019*',
    title: 'Jeff Manion - The Land Between',
    talk: 'The Land Between',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'Auditorium',
    subtitle: 'Brookfield',
    speaker: 'Jeff Manion',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10020,
    barcode: '*10020*',
    title: 'Kyle LeMieux - Redeeming Youth Sports',
    talk: 'Redeeming Youth Sports',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'B227',
    subtitle: 'Brookfield',
    speaker: 'Kyle LeMieux',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10021,
    barcode: '*10021*',
    title: 'Matt Erickson - To Work is to Worship',
    talk: 'To Work is to Worship',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'Amphitheater',
    subtitle: 'Brookfield',
    speaker: 'Matt Erickson',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10022,
    barcode: '*10022*',
    title: 'Mel Lawrenz - How to Study the Bible',
    talk: 'How to Study the Bible',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'B334-336',
    subtitle: 'Brookfield',
    speaker: 'Mel Lawrenz',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10023,
    barcode: '*10023*',
    title: 'Michael Daniels - Becoming Mr. Right',
    talk: 'Becoming Mr. Right',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'B228',
    subtitle: 'Brookfield',
    speaker: 'Michael Daniels',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10024,
    barcode: '*10024*',
    title: 'Nick Stumbo - Sexual Integrity',
    talk: 'Sexual Integrity',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'B325-328',
    subtitle: 'Brookfield',
    speaker: 'Nick Stumbo',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10025,
    barcode: '*10025*',
    title: 'Ralph Mierow - Temptations',
    talk: 'Temptations',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'B329-332',
    subtitle: 'Brookfield',
    speaker: 'Ralph Mierow',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10026,
    barcode: '*10026*',
    title: 'Steve Mayer - Defending Your Faith',
    talk: 'Defending Your Faith',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'D166-167',
    subtitle: 'Brookfield',
    speaker: 'Steve Mayer',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10027,
    barcode: '*10027*',
    title: 'Troy Thomas - Friendship',
    talk: 'Friendship',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'B223-226',
    subtitle: 'Brookfield',
    speaker: 'Troy Thomas',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10028,
    barcode: '*10028*',
    title: 'Spanish 2',
    talk: 'Spanish 2',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'D168',
    subtitle: 'Brookfield',
    additionallabel: "No Regrets Men's Conference 2021",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10029,
    barcode: '*10029*',
    title: 'Brady Boyd - Remarkable Marriage',
    talk: 'Remarkable Marriage',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'Auditorium',
    subtitle: 'Brookfield',
    speaker: 'Brady Boyd',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10030,
    barcode: '*10030*',
    title: 'Brian Episcopo - I am a parent, now what?',
    talk: 'I am a parent, now what?',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'B229',
    subtitle: 'Brookfield',
    speaker: 'Brian Episcopo',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10031,
    barcode: '*10031*',
    title: 'Brian & Melissa Hofmeister - Intimacy in Marriage',
    talk: 'Intimacy in Marriage',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'B231-232',
    subtitle: 'Brookfield',
    speaker: 'Brian and Melissa Hofmeister',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10032,
    barcode: '*10032*',
    title: 'Jeff Jaeger - Sharing His Story while Sharing Yours',
    talk: 'Sharing His Story while Sharing Yours',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'B321-324',
    subtitle: 'Brookfield',
    speaker: 'Jeff Jaeger',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10033,
    barcode: '*10033*',
    title: 'Matt Erickson - To Work is to Worship',
    talk: 'To Work is to Worship',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'Amphitheater',
    subtitle: 'Brookfield',
    speaker: 'Matt Erickson',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10034,
    barcode: '*10034*',
    title: 'Matthew Malone - Consumed by Technology',
    talk: 'Consumed by Technology',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'B227',
    subtitle: 'Brookfield',
    speaker: 'Matthew Malone',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10035,
    barcode: '*10035*',
    title: 'Mel Lawrenz - How to Study the Bible',
    talk: 'How to Study the Bible',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'B334-336',
    subtitle: 'Brookfield',
    speaker: 'Mel Lawrenz',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10036,
    barcode: '*10036*',
    title: 'Michael Daniels - Becoming Mr. Right',
    talk: 'Becoming Mr. Right',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'B228',
    subtitle: 'Brookfield',
    speaker: 'Michael Daniels',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10037,
    barcode: '*10037*',
    title: 'Nick Stumbo - Sexual Integrity',
    talk: 'Sexual Integrity',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'B325-328',
    subtitle: 'Brookfield',
    speaker: 'Nick Stumbo',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10038,
    barcode: '*10038*',
    title: 'Ralph Mierow - Temptations',
    talk: 'Temptations',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'B329-332',
    subtitle: 'Brookfield',
    speaker: 'Ralph Mierow',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10039,
    barcode: '*10039*',
    title: 'Skye Jethani - Redeeming Work',
    talk: 'Redeeming Work',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'Chapel',
    subtitle: 'Brookfield',
    speaker: 'Skye Jethani',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10040,
    barcode: '*10040*',
    title: 'Steve Mayer - Defending Your Faith',
    talk: 'Defending Your Faith',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'D166-167',
    subtitle: 'Brookfield',
    speaker: 'Steve Mayer',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10041,
    barcode: '*10041*',
    title: 'Troy Thomas - Friendship',
    talk: 'Friendship',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'B223-226',
    subtitle: 'Brookfield',
    speaker: 'Troy Thomas',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10042,
    barcode: '*10042*',
    title: 'Spanish 3',
    talk: 'Spanish 3',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'D168',
    subtitle: 'Brookfield',
    additionallabel: "No Regrets Men's Conference 2022",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10043,
    barcode: '*10043*',
    title: 'Brian Sonderman - The Workday Weekday Blues',
    talk: 'The Workday Weekday Blues',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'B329-332',
    subtitle: 'Brookfield',
    speaker: 'Brian Sonderman',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10044,
    barcode: '*10044*',
    title: 'Brian Marvel - Adversity',
    talk: 'Adversity',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'B223-226',
    subtitle: 'Brookfield',
    speaker: 'Bryan Marvel',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10045,
    barcode: '*10045*',
    title: 'Casey Seymour - Parenting Through the Seasons',
    talk: 'Parenting Through the Seasons',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'B321-324',
    subtitle: 'Brookfield',
    speaker: 'Casey Seymour',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10046,
    barcode: '*10046*',
    title: 'Colleen Sonderman - Top Ten Things Every Wife Wishes Her Husband Knew',
    talk: 'Top Ten Things Every Wife Wishes Her Husband Knew',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'B231-232',
    subtitle: 'Brookfield',
    speaker: 'Colleen Sonderman',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10047,
    barcode: '*10047*',
    title: 'Elie Hasbani - Biblical Healing for Past Wounds',
    talk: 'Biblical Healing for Past Wounds',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'D166-167',
    subtitle: 'Brookfield',
    speaker: 'Elie Hasbani',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10048,
    barcode: '*10048*',
    title: 'Jeff Manion - Dream Big, Think Small',
    talk: 'Dream Big, Think Small',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'Chapel',
    subtitle: 'Brookfield',
    speaker: 'Jeff Manion',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10049,
    barcode: '*10049*',
    title: 'Kyle LeMieux - Redeeming Youth Sports',
    talk: 'Redeeming Youth Sports',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'B227',
    subtitle: 'Brookfield',
    speaker: 'Kyle LeMieux',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10050,
    barcode: '*10050*',
    title: "Kyle Frier - How to Start a Men's Small Group",
    talk: "How to Start a Men's Small Group",
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'B229',
    subtitle: 'Brookfield',
    speaker: 'Kyle Frier',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10051,
    barcode: '*10051*',
    title: 'Nic Gibson - Sexual Identity',
    talk: 'Sexual Identity',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'B228',
    subtitle: 'Brookfield',
    speaker: 'Nic Gibson',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10052,
    barcode: '*10052*',
    title: 'Nick Stumbo - Launching an Effective and Sustainable Healing Ministry in Your Church',
    talk: 'Launching an Effective and Sustainable Healing Ministry in Your Church',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'B325-328',
    subtitle: 'Brookfield',
    speaker: 'Nick Stumbo',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10053,
    barcode: '*10053*',
    title: 'Norm Hubbard - A Growing Prayer Life',
    talk: 'A Growing Prayer Life',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'B334-336',
    subtitle: 'Brookfield',
    speaker: 'Norm Hubbard',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10054,
    barcode: '*10054*',
    title: 'Paul Stevens - Biblical Manhood',
    talk: 'Biblical Manhood',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'Amphitheater',
    subtitle: 'Brookfield',
    speaker: 'Paul Stevens',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10055,
    barcode: '*10055*',
    title: 'Skye Jethani - Culture and Christ',
    talk: 'Culture and Christ',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'Auditorium',
    subtitle: 'Brookfield',
    speaker: 'Skye Jethani',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10056,
    barcode: '*10056*',
    title: 'Spanish 4',
    talk: 'Spanish 4',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'D168',
    subtitle: 'Brookfield',
    additionallabel: "No Regrets Men's Conference 2023",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10057,
    barcode: '*10057*',
    title: 'Gary Haugen - Uncommon',
    talk: 'Uncommon',
    seminar: 'Afternoon General Session',
    time: '2:15-4:00 PM',
    room: 'Auditorium',
    subtitle: 'Brookfield',
    speaker: 'Gary Haugen',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10058,
    barcode: '*10058*',
    title: 'Jerod Walker - Three Financial Measures Every Church Leader Should Know',
    talk: 'Three Financial Measures Every Church Leader Should Know',
    seminar: 'EB',
    time: '7:30 – 8:15 AM',
    room: 'B321-324',
    subtitle: 'Brookfield',
    speaker: 'Jerod Walker',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10059,
    barcode: '*10059*',
    title: 'Lee Heyward - When Conflict Collides With...Your Happily Ever After',
    talk: 'When Conflict Collides With...Your Happily Ever After',
    seminar: 'EB',
    time: '7:30 – 8:15 AM',
    room: 'B325-328',
    subtitle: 'Brookfield',
    speaker: 'Lee Heyward',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10060,
    barcode: '*10060*',
    title: 'Matt Erickson - To Work is to Worship',
    talk: 'To Work is to Worship',
    seminar: 'EB',
    time: '7:30 – 8:15 AM',
    room: 'B223-226',
    subtitle: 'Brookfield',
    speaker: 'Matt Erickson',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10064,
    barcode: '*10064*',
    title: "Dan Schober - Exploring God's Sovereignty and Man's Free Will",
    talk: 'Exploring God’s Sovereignty and Man’s Free Will',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'Room 220 Upper Room',
    subtitle: 'Lake Country',
    speaker: 'Dan Schober',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10065,
    barcode: '*10065*',
    title: 'Lloyd Biddle - Working it Out-Marriage and Career',
    talk: 'Working it Out-Marriage and Career',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'Room 120',
    subtitle: 'Lake Country',
    speaker: 'Lloyd Biddle',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10066,
    barcode: '*10066*',
    title: 'Luke Dye - Straight Talk',
    talk: 'Straight Talk',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'Gym',
    subtitle: 'Lake Country',
    speaker: 'Luke Dye',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10067,
    barcode: '*10067*',
    title: 'Mark Hancock - The Power of a Shared Life',
    talk: 'The Power of a Shared Life',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'Room 121',
    subtitle: 'Lake Country',
    speaker: 'Mark Hancock',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10068,
    barcode: '*10068*',
    title: 'Michael Wright - What Love Looks Like-Living Lives of Grace & Truth',
    talk: 'What Love Looks Like-Living Lives of Grace & Truth',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'Room 123',
    subtitle: 'Lake Country',
    speaker: 'Michael Wright',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10069,
    barcode: '*10069*',
    title: 'Scott Jansen - Living Boldly for the Lord',
    talk: 'Living Boldly for the Lord',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'Room 125',
    subtitle: 'Lake Country',
    speaker: 'Scott Jansen',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10070,
    barcode: '*10070*',
    title: 'Stuart Briscoe - Temptation is a Test!',
    talk: 'Temptation is a Test!',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'Chapel',
    subtitle: 'Lake Country',
    speaker: 'Stuart Briscoe',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10071,
    barcode: '*10071*',
    title: 'Warren Widicus - 50+ Now What?',
    talk: '50+ Now What?',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'Room 128',
    subtitle: 'Lake Country',
    speaker: 'Warren Widicus',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10072,
    barcode: '*10072*',
    title: 'Andrew Johnston - Seven Things Your Pastor Wished You Knew',
    talk: 'Seven Things Your Pastor Wished You Knew',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'Room 120',
    subtitle: 'Lake Country',
    speaker: 'Andrew Johnston',
    additionallabel: "No Regrets Men's Conference 2021",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10073,
    barcode: '*10073*',
    title: 'Jeff Schultz - Can I Give God My First Fruits and Still Pay My Bills?',
    talk: 'Can I Give God My First Fruits and Still Pay My Bills?',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'Room 125',
    subtitle: 'Lake Country',
    speaker: 'Jeff Schultz',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10074,
    barcode: '*10074*',
    title: 'Mac McCarthy - Failure to Launch',
    talk: 'Failure to Launch',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'Chapel',
    subtitle: 'Lake Country',
    speaker: 'Mac McCarthy',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10075,
    barcode: '*10075*',
    title: 'Mark Hancock - The Power of a Shared Life',
    talk: 'The Power of a Shared Life',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'Room 121',
    subtitle: 'Lake Country',
    speaker: 'Mark Hancock',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10076,
    barcode: '*10076*',
    title: 'Mike Beresford - Intimacy in Marriage-What Your Wife Asked Me to Tell You',
    talk: 'Intimacy in Marriage-What Your Wife Asked Me to Tell You',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'Room 122',
    subtitle: 'Lake Country',
    speaker: 'Mike Beresford',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10077,
    barcode: '*10077*',
    title: "Nathan Stenholtz - It's Time to Get SIRI-us About Evangelism!",
    talk: "It's Time to Get SIRI-us About Evangelism!",
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'Room 128',
    subtitle: 'Lake Country',
    speaker: 'Nathan Stenholtz',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10078,
    barcode: '*10078*',
    title: 'Steve Sonderman - Leaving a Legacy',
    talk: 'Leaving a Legacy',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'Auditorium',
    subtitle: 'Lake Country',
    speaker: 'Steve Sonderman',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10079,
    barcode: '*10079*',
    title: 'Troy Loether - Parenting on Purpose',
    talk: 'Parenting on Purpose',
    seminar: 2,
    time: '11:15 – 12:00 PM',
    room: 'Room 220 Upper Room',
    subtitle: 'Lake Country',
    speaker: 'Troy Loether',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10080,
    barcode: '*10080*',
    title: "Dan Schober - Exploring God's Sovereignty and Man's Free Will",
    talk: 'Exploring God’s Sovereignty and Man’s Free Will',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'Room 128',
    subtitle: 'Lake Country',
    speaker: 'Dan Schober',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10081,
    barcode: '*10081*',
    title: 'Lloyd Biddle - Working it Out-Marriage and Career',
    talk: 'Working it Out-Marriage and Career',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'Room 120',
    subtitle: 'Lake Country',
    speaker: 'Lloyd Biddle',
    additionallabel: "No Regrets Men's Conference 2021",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10082,
    barcode: '*10082*',
    title: 'Luke Dye - Straight Talk',
    talk: 'Straight Talk',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'Chapel',
    subtitle: 'Lake Country',
    speaker: 'Luke Dye',
    additionallabel: "No Regrets Men's Conference 2021",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10083,
    barcode: '*10083*',
    title: 'Luke Zeka - Pressed but not Crushed-Good news for young men living in a stress-filled world',
    talk: 'Pressed but not Crushed-Good news for young men living in a stress',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'Room 123',
    subtitle: 'Lake Country',
    speaker: 'Luke Zeka',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10084,
    barcode: '*10084*',
    title: 'Mark Hancock - The Power of a Shared Life',
    talk: 'The Power of a Shared Life',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'Room 121',
    subtitle: 'Lake Country',
    speaker: 'Mark Hancock',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10085,
    barcode: '*10085*',
    title: 'Scott Jansen - Living Boldly for the Lord',
    talk: 'Living Boldly for the Lord',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'Room 125',
    subtitle: 'Lake Country',
    speaker: 'Scott Jansen',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10086,
    barcode: '*10086*',
    title: 'Warren Widicus - 50+ Now What?',
    talk: '50+ Now What?',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'Room 220 Upper Room',
    subtitle: 'Lake Country',
    speaker: 'Warren Widicus',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10087,
    barcode: '*10087*',
    title: 'Andrew Johnston - Seven Things Your Pastor Wished You Knew',
    talk: 'Seven Things Your Pastor Wished You Knew',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'Room 120',
    subtitle: 'Lake Country',
    speaker: 'Andrew Johnston',
    additionallabel: "No Regrets Men's Conference 2022",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10088,
    barcode: '*10088*',
    title: 'Jeff Schultz - Can I Give God My First Fruits and Still Pay My Bills?',
    talk: 'Can I Give God My First Fruits and Still Pay My Bills?',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'Room 220 Upper Room',
    subtitle: 'Lake Country',
    speaker: 'Jeff Schultz',
    additionallabel: "No Regrets Men's Conference 2021",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10089,
    barcode: '*10089*',
    title: 'Mac McCarthy - Failure to Launch',
    talk: 'Failure to Launch',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'Chapel',
    subtitle: 'Lake Country',
    speaker: 'Mac McCarthy',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10090,
    barcode: '*10090*',
    title: 'Mike Beresford - Intimacy in Marriage-What Your Wife Asked Me to Tell You',
    talk: 'Intimacy in Marriage-What Your Wife Asked Me to Tell You',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'Room 122',
    subtitle: 'Lake Country',
    speaker: 'Mike Beresford',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10091,
    barcode: '*10091*',
    title: "Nathan Stenholtz - It's Time to Get SIRI-us About Evangelism!",
    talk: "It's Time to Get SIRI-us About Evangelism!",
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'Room 128',
    subtitle: 'Lake Country',
    speaker: 'Nathan Stenholtz',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10092,
    barcode: '*10092*',
    title: "Ned Frost and Ron Fickel, MD - Men's Health",
    talk: "Men's Health",
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'Room 121',
    subtitle: 'Lake Country',
    speaker: 'Ned Frost and Ron Fickel, MD'
  },
  {
    id: 10093,
    barcode: '*10093*',
    title: 'Stuart Briscoe - Temptation is a Test!',
    talk: 'Temptation is a Test!',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'Gym',
    subtitle: 'Lake Country',
    speaker: 'Stuart Briscoe',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10094,
    barcode: '*10094*',
    title: 'Troy Loether - Parenting on Purpose',
    talk: 'Parenting on Purpose',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'Room 125',
    subtitle: 'Lake Country',
    speaker: 'Troy Loether',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10095,
    barcode: '*10095*',
    title: 'Will Branch - How Young Men Can Stay Pure in the Age of Sexual Brokenness?',
    talk: 'How Young Men Can Stay Pure in the Age of Sexual Brokenness?',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'Room 123',
    subtitle: 'Lake Country',
    speaker: 'Will Branch',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10096,
    barcode: '*10096*',
    title: 'Albo Esilaba - Last Man Standing',
    talk: 'Last Man Standing',
    seminar: '?',
    time: '#N/A',
    room: '?',
    subtitle: 'Lake Country',
    speaker: 'Albo Esilaba',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10097,
    barcode: '*10097*',
    title: 'Dave Lovett - Understanding Muslims and the Middle East-How Do We Engage the World of Islam?',
    talk: 'Understanding Muslims and the Middle East-How Do We Engage the World of Islam?',
    seminar: '?',
    time: '#N/A',
    room: '?',
    subtitle: 'Lake Country',
    speaker: 'Dave Lovett',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10098,
    barcode: '*10098*',
    title: 'Andrew Johnston - Seven Things Your Pastor Wished You Knew',
    talk: 'Seven Things Your Pastor Wished You Knew',
    seminar: 'EB',
    time: '7:30 – 8:15 AM',
    room: 'Room 111/112',
    subtitle: 'Lake Country',
    speaker: 'Andrew Johnston',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10099,
    barcode: '*10099*',
    title: 'Matthew Malone - Forgiveness',
    talk: 'Forgiveness',
    seminar: 'EB',
    time: '7:30 – 8:15 AM',
    room: 'Amphitheater',
    subtitle: 'Brookfield',
    speaker: 'Matthew Malone',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10100,
    barcode: '*10100*',
    title: 'Mel Lawrenz - How to Study the Bible',
    talk: 'How to Study the Bible',
    seminar: 'EB',
    time: '7:30 – 8:15 AM',
    room: 'Fellowship Hall',
    subtitle: 'Brookfield',
    speaker: 'Mel Lawrenz',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10101,
    barcode: '*10101*',
    title: 'Steve Mayer - Fire Away! Exploring Faiths Toughest Questions',
    talk: 'Fire Away! Exploring Faiths Toughest Questions',
    seminar: 'EB',
    time: '7:30 – 8:15 AM',
    room: 'Chapel',
    subtitle: 'Lake Country',
    speaker: 'Steve Mayer',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Breakout Seminar from 2020 No Regrets Men's Conference"
  },
  {
    id: 10102,
    barcode: '*10102*',
    title: 'Albert Tate - Uncommon',
    talk: 'Uncommon',
    seminar: 'Morning General Session',
    time: '8:30-10:00 AM',
    room: 'Auditorium',
    subtitle: 'Brookfield',
    speaker: 'Albert Tate',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10103,
    barcode: '*10103*',
    title: 'Albert Tate - Uncommon Parenting',
    talk: 'Uncommon Parenting',
    seminar: 4,
    time: '1:15 – 2:00 PM',
    room: 'Auditorium',
    subtitle: 'Lake Country',
    speaker: 'Albert Tate',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10104,
    barcode: '*10104*',
    title: 'Carlos Whittake - "Kill the Spider"',
    talk: '"Kill the Spider"',
    seminar: 3,
    time: '12:15 – 1:00 PM',
    room: 'Auditorium',
    subtitle: 'Lake Country',
    speaker: 'Carlos Whittake',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  },
  {
    id: 10105,
    barcode: '*10105*',
    title: 'Skye Jethani - Redeeming Work',
    talk: 'Redeeming Work',
    seminar: 1,
    time: '10:15-11:00 AM',
    room: 'Auditorium',
    subtitle: 'Lake Country',
    speaker: 'Skye Jethani',
    additionallabel: "No Regrets Men's Conference 2020",
    summary: "Platform Session from 2020 No Regrets Men's Conference"
  }
]

export const itemsMap = items.reduce((accum, item) => {
  accum[item.id] = item
  return accum
}, {})

export default items
